### ISSUE TITLE
[BUG-FIX] mobile-bing-login-loop > hamburger blocked by cookie accept

### ISSUE THREAD

**Issue by zosky** [charlesbel/Microsoft-Rewards-Farmer#187]
mobile bing login gets stuck in a loop ... looks like (now?) the hamburger is disabled until cookies accepted. _(thnx GDPR?)_

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/112049/e8edba0b-b70e-48be-a824-20faf53626c0)

- if *by hand* i click `a#bnp_ttc_btn` i see a cookie change, but also it follows the `href`
- when i go back, the bar is gone - the hamburger works now. 
- i tried adding `.click()` & returning but didn't work
- i made it go away ... collected the mobile points

this is likely *not* the best solution, it's what i did to make the loop end. 
hope it helps, and thnx for sharing

``` 
#99    if isMobile:
+++        browser.execute_script("document.getElementById('bnp_ttc_div').style.display = 'none';")
```

**Comment by charlesbel** [comment]
Fixed with v3.0 #188

**Comment by zosky** [comment]
thanks for modularizing this w/ v3. 

still getting stuck on mobile login for me. 

i put the same *hack* at ` login.py#100 `

**Comment by charlesbel** [comment]
(Really) fixed it now
